# Load Dataset

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
DATA_PATH = "/content/drive/MyDrive/IT549_Lab2/movies.csv"
GLOVE_PATH = "/content/drive/MyDrive/IT549_Lab2/wiki_giga_2024_100_MFT20_vectors_seed_2024_alpha_0.75_eta_0.05.050_combined.txt"

# Task:1-Data Preparation

In [5]:
import pandas as pd

df = pd.read_csv(DATA_PATH)

df = df[['overview', 'tagline', 'keywords', 'genres', 'vote_average']]

df = df.dropna().reset_index(drop=True)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (3759, 5)

,overview,tagline,keywords,genres,vote_average
0,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,culture clash future space war space colony so...,Action Adventure Fantasy Science Fiction,7.2
1,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",ocean drug abuse exotic island east india trad...,Adventure Fantasy Action,6.9
2,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,spy based on novel secret agent sequel mi6,Action Adventure Crime,6.3
3,Following the death of District Attorney Harve...,The Legend Ends,dc comics crime fighter terrorist secret ident...,Action Crime Drama Thriller,7.6
4,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",based on novel mars medallion space travel pri...,Action Adventure Science Fiction,6.1

In [10]:
import re
import string
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [11]:
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = text.lower()

    text = re.sub(r'http\S+', '', text)

    text = re.sub(r'\d+', '', text)

    text = text.translate(str.maketrans('', '', string.punctuation))

    tokens = word_tokenize(text)

    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return tokens

In [12]:
df['overview_tokens'] = df['overview'].apply(preprocess)
df['tagline_tokens'] = df['tagline'].apply(preprocess)
df['keywords_tokens'] = df['keywords'].apply(preprocess)

In [13]:
df[['overview_tokens', 'tagline_tokens', 'keywords_tokens']].head()

,overview_tokens,tagline_tokens,keywords_tokens
0,"[in, the, nd, century, a, paraplegic, marine, ...","[enter, the, world, of, pandora]","[culture, clash, future, space, war, space, co..."
1,"[captain, barbossa, long, believed, to, be, de...","[at, the, end, of, the, world, the, adventure,...","[ocean, drug, abuse, exotic, island, east, ind..."
2,"[a, cryptic, message, from, bond, ’, s, past, ...","[a, plan, no, one, escape]","[spy, based, on, novel, secret, agent, sequel,..."
3,"[following, the, death, of, district, attorney...","[the, legend, end]","[dc, comic, crime, fighter, terrorist, secret,..."
4,"[john, carter, is, a, warweary, former, milita...","[lost, in, our, world, found, in, another]","[based, on, novel, mar, medallion, space, trav..."

In [14]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    random_state=42,
    shuffle=True
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42,
    shuffle=True
)

print("Train size:", len(train_df))
print("Validation size:", len(val_df))
print("Test size:", len(test_df))

Train size: 2631
Validation size: 564
Test size: 564

# Task 2 - GloVe Embedding Pipeline

Load GloVe (100D)

In [ ]:
import numpy as np

embedding_dim = 100

glove_dict = {}

with open(GLOVE_PATH, 'r', encoding='utf-8') as f:
    for line in f:
        values = line.split()
        if len(values) == 0:
            continue
        word = values[0]
        try:
            vector = np.asarray(values[1:], dtype='float32')
            glove_dict[word] = vector
        except ValueError:
            print(f"Skipping malformed line: {line.strip()} (word: '{word}', vector_part: '{values[1:]}')")
            continue

print("Total GloVe words loaded:", len(glove_dict))

In [17]:
all_tokens = set()

for col in ['overview_tokens', 'tagline_tokens', 'keywords_tokens']:
    for tokens in df[col]:
        all_tokens.update(tokens)

print("Total unique dataset tokens:", len(all_tokens))

Total unique dataset tokens: 19187

In [18]:
covered_tokens = [word for word in all_tokens if word in glove_dict]

coverage = len(covered_tokens) / len(all_tokens)

print("Embedding Coverage: {:.2%}".format(coverage))

Embedding Coverage: 91.86%

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

def build_tfidf_glove_embeddings(train_tokens, val_tokens, test_tokens):

    train_texts = train_tokens.apply(lambda x: " ".join(x))
    val_texts = val_tokens.apply(lambda x: " ".join(x))
    test_texts = test_tokens.apply(lambda x: " ".join(x))

    vectorizer = TfidfVectorizer()
    vectorizer.fit(train_texts)

    feature_names = vectorizer.get_feature_names_out()
    vocab_dict = {word: idx for idx, word in enumerate(feature_names)}

    def get_doc_embedding(texts):
        tfidf_matrix = vectorizer.transform(texts)
        doc_embeddings = []

        for i in range(tfidf_matrix.shape[0]):
            row = tfidf_matrix[i]
            indices = row.indices
            weights = row.data

            doc_vector = np.zeros(embedding_dim)
            weight_sum = 0

            for idx, weight in zip(indices, weights):
                word = feature_names[idx]

                if word in glove_dict:
                    doc_vector += weight * glove_dict[word]
                    weight_sum += weight

            if weight_sum != 0:
                doc_vector = doc_vector / weight_sum

            doc_embeddings.append(doc_vector)

        return np.array(doc_embeddings)

    X_train = get_doc_embedding(train_texts)
    X_val = get_doc_embedding(val_texts)
    X_test = get_doc_embedding(test_texts)

    return X_train, X_val, X_test

In [20]:
X_train_overview, X_val_overview, X_test_overview = build_tfidf_glove_embeddings(
    train_df['overview_tokens'],
    val_df['overview_tokens'],
    test_df['overview_tokens']
)

print("Shape:", X_train_overview.shape)

Shape: (2631, 100)

# Task 3 - Model A: Rating Prediction (Regression)

In [21]:
X_train_overview, X_val_overview, X_test_overview = build_tfidf_glove_embeddings(
    train_df['overview_tokens'],
    val_df['overview_tokens'],
    test_df['overview_tokens']
)

In [51]:
X_train_tagline, X_val_tagline, X_test_tagline = build_tfidf_glove_embeddings(
    train_df['tagline_tokens'],
    val_df['tagline_tokens'],
    test_df['tagline_tokens']
)

In [23]:
y_train = train_df['vote_average'].values
y_val = val_df['vote_average'].values
y_test = test_df['vote_average'].values

In [24]:
from sklearn.metrics import mean_squared_error
import numpy as np

mean_rating = y_train.mean()

baseline_preds = np.full_like(y_test, mean_rating)

baseline_mse = mean_squared_error(y_test, baseline_preds)
baseline_rmse = np.sqrt(baseline_mse)

print("Baseline MSE:", baseline_mse)
print("Baseline RMSE:", baseline_rmse)

Baseline MSE: 0.8976762200816473
Baseline RMSE: 0.9474577669118804

In [52]:
import torch

X_train_tensor = torch.tensor(X_train_overview, dtype=torch.float32)
X_val_tensor = torch.tensor(X_val_overview, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_overview, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1,1)
y_val_tensor = torch.tensor(y_val, dtype=torch.float32).view(-1,1)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1,1)


X_train_tensor_tag = torch.tensor(X_train_tagline, dtype=torch.float32)
X_val_tensor_tag = torch.tensor(X_val_tagline, dtype=torch.float32)
X_test_tensor_tag = torch.tensor(X_test_tagline, dtype=torch.float32)

y_train_tensor_tag = torch.tensor(y_train, dtype=torch.float32).view(-1,1)
y_val_tensor_tag = torch.tensor(y_val, dtype=torch.float32).view(-1,1)
y_test_tensor_tag = torch.tensor(y_test, dtype=torch.float32).view(-1,1)

In [27]:
import torch.nn as nn

class RegressionModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 1)
        )

    def forward(self, x):
        return self.model(x)

In [29]:
model = RegressionModel(input_dim=100)

In [30]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [31]:
epochs = 20

for epoch in range(epochs):

    model.train()
    optimizer.zero_grad()

    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)

    loss.backward()
    optimizer.step()

    # Validation loss
    model.eval()
    with torch.no_grad():
        val_outputs = model(X_val_tensor)
        val_loss = criterion(val_outputs, y_val_tensor)

    print(f"Epoch {epoch+1}/{epochs} | Train Loss: {loss.item():.4f} | Val Loss: {val_loss.item():.4f}")

Epoch 1/20 | Train Loss: 39.9340 | Val Loss: 39.2889
Epoch 2/20 | Train Loss: 39.2787 | Val Loss: 38.5747
Epoch 3/20 | Train Loss: 38.6080 | Val Loss: 37.8230
Epoch 4/20 | Train Loss: 37.9051 | Val Loss: 37.0394
Epoch 5/20 | Train Loss: 37.1724 | Val Loss: 36.2361
Epoch 6/20 | Train Loss: 36.4153 | Val Loss: 35.4035
Epoch 7/20 | Train Loss: 35.6269 | Val Loss: 34.5255
Epoch 8/20 | Train Loss: 34.7939 | Val Loss: 33.5949
Epoch 9/20 | Train Loss: 33.9078 | Val Loss: 32.6049
Epoch 10/20 | Train Loss: 32.9641 | Val Loss: 31.5513
Epoch 11/20 | Train Loss: 31.9587 | Val Loss: 30.4302
Epoch 12/20 | Train Loss: 30.8880 | Val Loss: 29.2395
Epoch 13/20 | Train Loss: 29.7496 | Val Loss: 27.9788
Epoch 14/20 | Train Loss: 28.5425 | Val Loss: 26.6459
Epoch 15/20 | Train Loss: 27.2640 | Val Loss: 25.2358
Epoch 16/20 | Train Loss: 25.9092 | Val Loss: 23.7435
Epoch 17/20 | Train Loss: 24.4739 | Val Loss: 22.1734
Epoch 18/20 | Train Loss: 22.9601 | Val Loss: 20.5323
Epoch 19/20 | Train Loss: 21.3734 | Val Loss: 18.8263
Epoch 20/20 | Train Loss: 19.7200 | Val Loss: 17.0649

In [32]:
model.eval()

with torch.no_grad():
    test_preds = model(X_test_tensor)

test_preds = test_preds.numpy()
y_test_np = y_test_tensor.numpy()

mse = mean_squared_error(y_test_np, test_preds)
rmse = np.sqrt(mse)

print("Neural Model MSE:", mse)
print("Neural Model RMSE:", rmse)

Neural Model MSE: 16.742835998535156
Neural Model RMSE: 4.091801070254412

In [53]:
model_tag = RegressionModel(input_dim=100)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model_tag.parameters(), lr=0.001)

In [54]:
for epoch in range(20):

    model_tag.train()
    optimizer.zero_grad()

    outputs = model_tag(X_train_tensor_tag)
    loss = criterion(outputs, y_train_tensor_tag)

    loss.backward()
    optimizer.step()

In [55]:
model_tag.eval()

with torch.no_grad():
    preds_tag = model_tag(X_test_tensor_tag)

preds_tag = preds_tag.numpy()

mse_tag = mean_squared_error(y_test, preds_tag)
rmse_tag = np.sqrt(mse_tag)

print("Tagline RMSE:", rmse_tag)

Tagline RMSE: 4.478024468365189

In [57]:
print("Overview RMSE:", rmse)
print("Tagline RMSE:", rmse_tag)

Overview RMSE: 4.091801070254412
Tagline RMSE: 4.478024468365189

In [59]:
results = {
    "Overview": rmse,
    "Tagline": rmse_tag
}

results

{'Overview': np.float64(4.091801070254412),
 'Tagline': np.float64(4.478024468365189)}

# Task 4 - Model B: Genre Prediction (Multi-Label Classification)

In [34]:
from sklearn.preprocessing import MultiLabelBinarizer

df['genre_list'] = df['genres'].apply(lambda x: [g.strip() for g in x.split(',')])

mlb = MultiLabelBinarizer()

genre_encoded = mlb.fit_transform(df['genre_list'])

num_classes = len(mlb.classes_)

print("Number of genres:", num_classes)
print("Genres:", mlb.classes_)

Number of genres: 1024
Genres: ['Action' 'Action Adventure' 'Action Adventure Animation Comedy Family'
 ... 'Western Drama Adventure Thriller' 'Western History'
 'Western History War']

In [35]:
train_df['genre_encoded'] = list(genre_encoded[train_df.index])
val_df['genre_encoded'] = list(genre_encoded[val_df.index])
test_df['genre_encoded'] = list(genre_encoded[test_df.index])

In [100]:
import torch.nn as nn

class GenreClassifier(nn.Module):
    def __init__(self, input_dim, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        return self.model(x)

In [101]:
from sklearn.metrics import f1_score, hamming_loss, jaccard_score
import torch

def run_multilabel_experiment(column_name):


    X_train, X_val, X_test = build_tfidf_glove_embeddings(
        train_df[column_name],
        val_df[column_name],
        test_df[column_name]
    )

    y_train = np.array(list(train_df['genre_encoded']))
    y_val = np.array(list(val_df['genre_encoded']))
    y_test = np.array(list(test_df['genre_encoded']))

    X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
    X_val_tensor = torch.tensor(X_val, dtype=torch.float32)
    X_test_tensor = torch.tensor(X_test, dtype=torch.float32)

    y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
    y_val_tensor = torch.tensor(y_val, dtype=torch.float32)
    y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

    model = GenreClassifier(input_dim=100, num_classes=num_classes)

    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    epochs = 20

    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()

        outputs = model(X_train_tensor)
        loss = criterion(outputs, y_train_tensor)

        loss.backward()
        optimizer.step()

    # Evaluation
    model.eval()
    with torch.no_grad():
        logits = model(X_test_tensor)
        probs = torch.sigmoid(logits)

    # Convert probabilities to binary predictions
    preds = (probs > 0.15).int().numpy()
    y_test_np = y_test_tensor.numpy()

    # Metrics
    micro_f1 = f1_score(y_test_np, preds, average='micro',zero_division=0)
    macro_f1 = f1_score(y_test_np, preds, average='macro',zero_division=0)
    hamming = hamming_loss(y_test_np, preds)
    jaccard = jaccard_score(y_test_np, preds, average='micro')

    return micro_f1, macro_f1, hamming, jaccard

In [102]:
micro_o, macro_o, ham_o, jac_o = run_multilabel_experiment('overview_tokens')

print("Overview Results")
print("Micro-F1:", micro_o)
print("Macro-F1:", macro_o)
print("Hamming Loss:", ham_o)
print("Jaccard Score:", jac_o)

Overview Results
Micro-F1: 0.002108860141567
Macro-F1: 0.0007770996995544681
Hamming Loss: 0.17697424922429078
Jaccard Score: 0.0010555430671344939

In [103]:
micro_t, macro_t, ham_t, jac_t = run_multilabel_experiment('tagline_tokens')

print("Tagline Results")
print("Micro-F1:", micro_t)
print("Macro-F1:", macro_t)
print("Hamming Loss:", ham_t)
print("Jaccard Score:", jac_t)

Tagline Results
Micro-F1: 0.0022172949002217295
Macro-F1: 0.0012906405689373397
Hamming Loss: 0.043633643617021274
Jaccard Score: 0.0011098779134295228

In [65]:
results = {
    "Overview": [micro_o, macro_o, ham_o, jac_o],
    "Tagline": [micro_t, macro_t, ham_t, jac_t]
}

results

{'Overview': [0.0018601463641481264,
  0.0007820858632937822,
  0.21183614527925532,
  np.float64(0.0009309390234939611)],
 'Tagline': [0.0018339706381300836,
  0.0005416901740741729,
  0.18847829399379432,
  np.float64(0.0009178269529062991)]}

# Task 5 - Frequent Words per Genre

In [68]:
from collections import Counter
import pandas as pd
df['genre_list'] = df['genres'].apply(lambda x: [g.strip() for g in x.split(',')])

In [69]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [76]:
def analyze_genre_words_clean(df, text_column='overview_tokens', min_freq=3):

    results = []

    all_genres = sorted(set(g for sublist in df['genre_list'] for g in sublist))

    for genre in all_genres:

        genre_movies = df[df['genre_list'].apply(lambda x: genre in x)]

        all_words = []

        for tokens in genre_movies[text_column]:
            filtered = [
                w for w in tokens
                if w not in stop_words
                and len(w) > 3
                and w.isalpha()
            ]
            all_words.extend(filtered)

        word_counts = Counter(all_words)

        top_10 = word_counts.most_common(10)

        valid_words = [(w, c) for w, c in word_counts.items() if c >= min_freq]
        valid_words_sorted = sorted(valid_words, key=lambda x: x[1])
        bottom_10 = valid_words_sorted[:10]

        for word, count in top_10:
            results.append([genre, "Top", word, count])

        for word, count in bottom_10:
            results.append([genre, "Bottom", word, count])

    result_df = pd.DataFrame(results, columns=["Genre", "Type", "Word", "Frequency"])

    return result_df

In [77]:
df['genre_list'] = df['genres'].apply(lambda x: [g.strip() for g in x.split(',')])

freq_table = analyze_genre_words_clean(df, text_column='overview_tokens')

freq_table.head(20)

     Genre    Type     Word  Frequency
0   Action     Top  brother          5
1   Action     Top     must          5
2   Action     Top    terry          5
3   Action     Top     gang          4
4   Action     Top    agent          4
5   Action     Top     star          3
6   Action     Top   fellow          3
7   Action     Top     take          3
8   Action     Top  fighter          3
9   Action     Top    biker          3
10  Action  Bottom     star          3
11  Action  Bottom   fellow          3
12  Action  Bottom     take          3
13  Action  Bottom  fighter          3
14  Action  Bottom    biker          3
15  Action  Bottom   murder          3
16  Action  Bottom     gang          4
17  Action  Bottom    agent          4
18  Action  Bottom  brother          5
19  Action  Bottom     must          5

In [78]:
for genre in freq_table['Genre'].unique():

    print("\n==============================")
    print(f"Genre: {genre}")

    print("\nTop 10 Frequent Words:")
    print(freq_table[(freq_table['Genre'] == genre) &
                     (freq_table['Type'] == 'Top')]
          [['Word', 'Frequency']]
          .reset_index(drop=True))

    print("\nBottom 10 Least Frequent Words (freq ≥ 3):")
    print(freq_table[(freq_table['Genre'] == genre) &
                     (freq_table['Type'] == 'Bottom')]
          [['Word', 'Frequency']]
          .reset_index(drop=True))

Streaming output truncated to the last 5000 lines.
0   alien          3
1    crew          3
2  planet          4

==============================
Genre: Horror Comedy

Top 10 Frequent Words:
       Word  Frequency
0   vampire          5
1      life          4
2     becca          3
3      town          3
4  werewolf          2
5    change          2
6     young          2
7      must          2
8   suspect          2
9    anyone          2

Bottom 10 Least Frequent Words (freq ≥ 3):
      Word  Frequency
0    becca          3
1     town          3
2     life          4
3  vampire          5

==============================
Genre: Horror Comedy Action Science Fiction Thriller

Top 10 Frequent Words:
             Word  Frequency
0           eaten          1
1           alive          1
2         unknown          1
3        creature          1
4           local          1
5            game          1
6          warden          1
7            team          1
8  paleontologist          1
9            york          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Comedy Crime

Top 10 Frequent Words:
          Word  Frequency
0    notorious          1
1    baltimore          1
2     criminal          1
3  underground          1
4       figure          1
5       divine          1
6       connie          1
7      raymond          1
8       marble          1
9       sleazy          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Comedy Crime Thriller

Top 10 Frequent Words:
          Word  Frequency
0       remote          1
1         part          1
2  countryside          1
3      bungled          1
4   kidnapping          1
5         turn          1
6       living          1
7    nightmare          1
8         four          1
9      central          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Comedy Fantasy

Top 10 Frequent Words:
      Word  Frequency
0    uncle          3
1   fester          3
2     evil          3
3   family          3
4   doctor          2
5     find          2
6     fake          2
7     adam          2
8  ancient          2
9    linda          2

Bottom 10 Least Frequent Words (freq ≥ 3):
     Word  Frequency
0   uncle          3
1  fester          3
2    evil          3
3  family          3

==============================
Genre: Horror Comedy Music

Top 10 Frequent Words:
         Word  Frequency
0       plant          3
1     seymour          2
2      audrey          2
3  mysterious          2
4    krelborn          1
5       nerdy          1
6      orphan          1
7     working          1
8    mushniks          1
9      flower          1

Bottom 10 Least Frequent Words (freq ≥ 3):
    Word  Frequency
0  plant          3

==============================
Genre: Horror Comedy Music Science Fiction

Top 10 Frequent Words:
             Word  Frequency
0       worldwide          1
1        epidemic          1
2      encourages          1
3         biotech          1
4         company          1
5          launch          1
6  organfinancing          1
7         program          1
8         similar          1
9          nature          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Comedy Romance

Top 10 Frequent Words:
         Word  Frequency
0      zombie          1
1     becomes          1
2    involved          1
3  girlfriend          1
4      victim          1
5     romance          1
6      motion          1
7    sequence          1
8       event          1
9       might          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Comedy Science Fiction

Top 10 Frequent Words:
          Word  Frequency
0       killer          1
1        named          1
2  cinderhella          1
3        stalk          1
4      student          1
5         body          1
6         high          1
7       school          1
8      grizzly          1
9         lake          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Comedy Thriller

Top 10 Frequent Words:
        Word  Frequency
0     hunted          1
1      demon          1
2      known          1
3  collector          1
4     member          1
5      danny          1
6       dyer          1
7      laura          1
8     harris          1
9  mcinnerny          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Crime

Top 10 Frequent Words:
       Word  Frequency
0    jigsaw          2
1  survivor          2
2    deadly          1
3    battle          1
4      rage          1
5    brutal          1
6    legacy          1
7     group          1
8    gather          1
9      seek          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Crime Thriller

Top 10 Frequent Words:
        Word  Frequency
0      young          1
1       punk          1
2       rock          1
3       band          1
4       find          1
5    trapped          1
6   secluded          1
7      venue          1
8  stumbling          1
9       upon          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Documentary Mystery

Top 10 Frequent Words:
          Word  Frequency
0  documentary          1
1    following          1
2    filmmaker          1
3       marino          1
4         head          1
5        italy          1
6  investigate          1
7     exorcism          1
8        truth          1
9       behind          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Drama Mystery

Top 10 Frequent Words:
        Word  Frequency
0      young          1
1     couple          1
2       move          1
3   infamous          1
4       york          1
5  apartment          1
6   building          1
7      start          1
8     family          1
9      thing          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Drama Mystery Thriller

Top 10 Frequent Words:
        Word  Frequency
0      grace          2
1      house          2
2      child          2
3  religious          1
4      woman          1
5       life          1
6       kept          1
7       dark          1
8       anne          1
9   nicholas          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Drama Science Fiction

Top 10 Frequent Words:
        Word  Frequency
0    hyunseo          5
1     gangdu          2
2     father          2
3      snack          2
4    gangdus          2
5     school          2
6      namil          2
7     object          2
8   creature          2
9  dimwitted          1

Bottom 10 Least Frequent Words (freq ≥ 3):
      Word  Frequency
0  hyunseo          5

==============================
Genre: Horror Drama Thriller

Top 10 Frequent Words:
       Word  Frequency
0      back          2
1    family          2
2  exorcism          2
3  reverend          2
4   injured          1
5    surfer          1
6  stranded          1
7      buoy          1
8      need          1
9     shore          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Drama Thriller Science Fiction

Top 10 Frequent Words:
        Word  Frequency
0       nazi          1
1     hunter          1
2       ezra          1
3  lieberman          1
4  discovers          1
5   sinister          1
6    bizarre          1
7       plot          1
8   rekindle          1
9      third          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Mystery

Top 10 Frequent Words:
          Word  Frequency
0       sidney          6
1         town          4
2         soon          4
3    woodsboro          4
4         past          4
5  premonition          4
6         save          4
7        death          4
8        group          4
9   terrifying          4

Bottom 10 Least Frequent Words (freq ≥ 3):
       Word  Frequency
0     young          3
1  daughter          3
2     begin          3
3      stop          3
4      life          3
5      book          3
6    return          3
7      gale          3
8   student          3
9      year          3

==============================
Genre: Horror Mystery Crime

Top 10 Frequent Words:
       Word  Frequency
0    victim          2
1      life          2
2      must          2
3  obsessed          1
4  teaching          1
5     value          1
6  deranged          1
7  sadistic          1
8    serial          1
9    killer          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Mystery Science Fiction

Top 10 Frequent Words:
       Word  Frequency
0      mask          3
1     alien          2
2    people          2
3   another          2
4     begin          2
5  unlikely          2
6   station          2
7    scheme          2
8   company          2
9     mazzy          2

Bottom 10 Least Frequent Words (freq ≥ 3):
   Word  Frequency
0  mask          3

==============================
Genre: Horror Mystery Thriller

Top 10 Frequent Words:
     Word  Frequency
0  murder          6
1   emily          5
2    girl          5
3   begin          4
4    ship          4
5   jason          4
6  merrin          3
7  church          3
8    keep          3
9  museum          3

Bottom 10 Least Frequent Words (freq ≥ 3):
       Word  Frequency
0    merrin          3
1    church          3
2      keep          3
3    museum          3
4     crate          3
5  discover          3
6   brought          3
7    family          3
8    lilith          3
9     child          3

==============================
Genre: Horror Romance

Top 10 Frequent Words:
         Word  Frequency
0     vampire          1
1     relates          1
2        epic          1
3        life          1
4       story          1
5        love          1
6    betrayal          1
7  loneliness          1
8        dark          1
9      hunger          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Science Fiction

Top 10 Frequent Words:
      Word  Frequency
0   zombie          4
1  cortner          3
2  compton          3
3     cure          2
4     year          2
5    earth          2
6    human          2
7    could          2
8    jason          2
9     life          2

Bottom 10 Least Frequent Words (freq ≥ 3):
      Word  Frequency
0  cortner          3
1  compton          3
2   zombie          4

==============================
Genre: Horror Science Fiction Action

Top 10 Frequent Words:
        Word  Frequency
0    vampire          2
1       good          1
2     battle          1
3     zombie          1
4     trying          1
5       hide          1
6   identity          1
7    prevent          1
8  infection          1
9  spreading          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Science Fiction Mystery

Top 10 Frequent Words:
          Word  Frequency
0         year          2
1         even          2
2        group          1
3    astronaut          1
4         sent          1
5  investigate          1
6      salvage          1
7         long          1
8         lost          1
9     starship          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Science Fiction Thriller

Top 10 Frequent Words:
         Word  Frequency
0        ship          2
1  mysterious          2
2      inside          2
3      killer          2
4        life          2
5     century          1
6    battered          1
7     salvage          1
8       sends          1
9    distress          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Thriller

Top 10 Frequent Words:
     Word  Frequency
0    find         18
1   group         17
2    life         16
3   young         16
4  friend         15
5    home         13
6    year         12
7   house         12
8   world         11
9  family         11

Bottom 10 Least Frequent Words (freq ≥ 3):
       Word  Frequency
0  shocking          3
1  creature          3
2     could          3
3      york          3
4      site          3
5     known          3
6  thriller          3
7      take          3
8     gypsy          3
9      soul          3

==============================
Genre: Horror Thriller Adventure

Top 10 Frequent Words:
          Word  Frequency
0        shark          2
1   insatiable          1
2        great          1
3        white          1
4   terrorizes          1
5  townspeople          1
6        amity          1
7       island          1
8       police          1
9        chief          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Thriller Comedy

Top 10 Frequent Words:
          Word  Frequency
0    nightmare          3
1       street          2
2      thought          1
3         safe          1
4        sleep          1
5       freddy          1
6      krueger          1
7       return          1
8        sixth          1
9  installment          1

Bottom 10 Least Frequent Words (freq ≥ 3):
        Word  Frequency
0  nightmare          3

==============================
Genre: Horror Thriller Crime

Top 10 Frequent Words:
         Word  Frequency
0      jigsaw          5
1   detective          4
2      arrive          2
3   seemingly          2
4     hoffman          2
5        last          2
6  apprentice          2
7      amanda          2
8        game          2
9   terrified          2

Bottom 10 Least Frequent Words (freq ≥ 3):
        Word  Frequency
0  detective          4
1     jigsaw          5

==============================
Genre: Horror Thriller Drama

Top 10 Frequent Words:
         Word  Frequency
0      family          1
1  terrorized          1
2     demonic          1
3       force          1
4      moving          1
5        home          1
6        site          1
7      grisly          1
8  massmurder          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Thriller Fantasy

Top 10 Frequent Words:
         Word  Frequency
0     bizarre          1
1   nightmare          1
2      plague          1
3       regan          1
4     macneil          1
5        four          1
6        year          1
7  possession          1
8    exorcism          1
9       demon          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Thriller Fantasy Mystery

Top 10 Frequent Words:
        Word  Frequency
0     marrow          2
1      david          1
2     invite          1
3       nell          1
4      vance          1
5       theo          1
6       luke          1
7  sanderson          1
8      eerie          1
9   isolated          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Thriller Mystery

Top 10 Frequent Words:
      Word  Frequency
0   alexia          5
1   killer          4
2   family          3
3   couple          2
4     year          2
5   esther          2
6  michael          2
7     home          2
8   school          2
9     find          2

Bottom 10 Least Frequent Words (freq ≥ 3):
     Word  Frequency
0  family          3
1  killer          4
2  alexia          5

==============================
Genre: Horror Thriller Mystery Fantasy

Top 10 Frequent Words:
         Word  Frequency
0     freddys          2
1       nancy          2
2        back          1
3      badder          1
4        ever          1
5  historical          1
6     nemesis          1
7     satanic          1
8       snarl          1
9   pitchfork          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Horror Thriller Science Fiction

Top 10 Frequent Words:
        Word  Frequency
0     rachel          4
1      later          3
2      virus          3
3    mission          3
4       moon          3
5      forge          2
6  dangerous          2
7      human          2
8     animal          2
9       bond          2

Bottom 10 Least Frequent Words (freq ≥ 3):
      Word  Frequency
0    later          3
1    virus          3
2  mission          3
3     moon          3
4   rachel          4

==============================
Genre: Music

Top 10 Frequent Words:
           Word  Frequency
0        dancer          2
1         dance          2
2        former          1
3  professional          1
4     volunteer          1
5         teach          1
6          york          1
7        public          1
8        school          1
9        system          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Music Adventure Animation Action Comedy

Top 10 Frequent Words:
            Word  Frequency
0           team          4
1        america          3
2          world          3
3         police          2
4        destroy          2
5           gary          2
6        follows          1
7  international          1
8          force          1
9      dedicated          1

Bottom 10 Least Frequent Words (freq ≥ 3):
      Word  Frequency
0  america          3
1    world          3
2     team          4

==============================
Genre: Music Comedy

Top 10 Frequent Words:
        Word  Frequency
0      corky          2
1     sleazy          1
2       exec          1
3      offer          1
4      wayne          1
5      garth          1
6   contract          1
7       tape          1
8  latenight          1
9     public          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Music Comedy Action Crime

Top 10 Frequent Words:
        Word  Frequency
0       jake          1
1       blue          1
2       jail          1
3       team          1
4    brother          1
5     elwood          1
6    mission          1
7      raise          1
8       fund          1
9  orphanage          1

Bottom 10 Least Frequent Words (freq ≥ 3):
Empty DataFrame
Columns: [Word, Frequency]
Index: []

==============================
Genre: Music Comedy Drama

Top 10 Frequent Words:
            Word  Frequency
0         elliot          3
1          music          2
2       festival          2
3          story          1
4          tiber          1
5         family          1
6  inadvertently          1
7         played          1
8        pivotal          1

# Task 6 - Genre-Indicative Words Using TF-IDF

In [79]:
df['overview_clean'] = df['overview_tokens'].apply(lambda x: " ".join(x))

In [80]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words='english',
    min_df=3
)

X = vectorizer.fit_transform(df['overview_clean'])

In [82]:
from sklearn.preprocessing import MultiLabelBinarizer

df['genre_list'] = df['genres'].apply(lambda x: [g.strip() for g in x.split(',')])

mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(df['genre_list'])

genres = mlb.classes_

In [83]:
from sklearn.linear_model import LogisticRegression
import numpy as np

indicative_words = {}

feature_names = vectorizer.get_feature_names_out()

for i, genre in enumerate(genres):

    y = Y[:, i]

    if y.sum() < 10:
        continue

    clf = LogisticRegression(max_iter=2000)
    clf.fit(X, y)

    coef = clf.coef_[0]

    top_indices = np.argsort(coef)[-10:]

    top_words = [(feature_names[j], coef[j]) for j in reversed(top_indices)]

    indicative_words[genre] = top_words

In [84]:
for genre, words in indicative_words.items():

    print("\n==============================")
    print(f"Genre: {genre}")
    print("Top 10 Indicative Words:")

    for word, weight in words:
        print(f"{word:15} {weight:.4f}")

==============================
Genre: Action
Top 10 Indicative Words:
fighter         0.8650
brother         0.8045
terry           0.6763
bank            0.6052
fellow          0.5722
bring           0.5371
agent           0.5352
biker           0.5268
star            0.4915
toretto         0.4793

==============================
Genre: Action Adventure Comedy
Top 10 Indicative Words:
criminal        0.7277
mitchell        0.6294
protection      0.5733
bikers          0.5559
cousin          0.5490
thief           0.5482
delivery        0.5451
jackson         0.5016
obtain          0.5007
evil            0.4622

==============================
Genre: Action Adventure Drama Thriller
Top 10 Indicative Words:
prison          0.6172
thief           0.5548
sam             0.5221
copilot         0.5046
champion        0.4916
terrorist       0.4271
alive           0.4268
heavyweight     0.4045
plane           0.4042
advertisement   0.3979

==============================
Genre: Action Adventure Science Fiction
Top 10 Indicative Words:
earth           1.0178
world           0.9921
alien           0.8716
captain         0.7125
planet          0.6604
rogers          0.5737
group           0.5644
epic            0.5620
unprecedented   0.5478
chip            0.5442

==============================
Genre: Action Adventure Thriller
Top 10 Indicative Words:
barney          0.6837
mission         0.5969
commando        0.5680
general         0.5590
tunnel          0.5326
matrix          0.5324
destruction     0.5265
climber         0.5043
organization    0.4490
cohort          0.4378

==============================
Genre: Action Comedy
Top 10 Indicative Words:
dealer          1.0571
james           0.7945
reunites        0.7085
movie           0.6076
steal           0.5892
celebrity       0.5638
ben             0.5466
frank           0.5284
product         0.5219
car             0.4781

==============================
Genre: Action Comedy Crime
Top 10 Indicative Words:
cop             1.4304
detective       1.0829
drug            0.8079
partner         0.5929
uptight         0.5524
bounty          0.5377
diamond         0.5288
stealing        0.4804
protect         0.4601
crook           0.4570

==============================
Genre: Action Crime Drama Thriller
Top 10 Indicative Words:
officer         1.3131
corrupt         0.9322
cop             0.8995
police          0.7497
doublecrossed   0.6395
head            0.5957
joey            0.5708
narcotic        0.5513
walker          0.5408
assassinate     0.4991

==============================
Genre: Action Crime Thriller
Top 10 Indicative Words:
chinese         0.9482
drug            0.9353
gang            0.8544
undercover      0.7818
agent           0.7767
joe             0.7742
cop             0.6930
dealer          0.6498
shady           0.6382
brian           0.6377

==============================
Genre: Action Drama Thriller
Top 10 Indicative Words:
cia             0.9086
analyst         0.6340
ryan            0.5929
crash           0.5000
rally           0.4683
inmate          0.4667
dean            0.4588
bourne          0.4377
jack            0.4363
personal        0.4152

==============================
Genre: Action Science Fiction
Top 10 Indicative Words:
human           0.8298
ape             0.7634
humanity        0.6085
robot           0.5959
world           0.4896
caesar          0.4813
judge           0.4737
seth            0.4514
city            0.4499
cage            0.4448

==============================
Genre: Action Science Fiction Thriller
Top 10 Indicative Words:
government      0.6470
surrogate       0.6270
alternate       0.5781
union           0.5331
wright          0.4616
robot           0.4355
connor          0.4292
determine       0.4257
satellite       0.3523
capacity        0.3358

==============================
Genre: Action Thriller
Top 10 Indicative Words:
mcclane         1.5086
terrorist       1.1940
kidnapped       1.1874
operative       1.1304
cia             1.0695
stop            0.7826
security        0.7593
safe            0.6776
disgraced       0.6670
criminal        0.6476

==============================
Genre: Action Thriller Crime
Top 10 Indicative Words:
assassin        0.7761
wesley          0.7665
professional    0.6970
bishop          0.6191
requires        0.6055
heart           0.5939
murphy          0.5762
boston          0.5426
weaver          0.5117
cover           0.4781

==============================
Genre: Action Thriller Science Fiction
Top 10 Indicative Words:
future          0.9844
sarah           0.8172
connor          0.8138
prison          0.7709
point           0.5568
futuristic      0.5478
control         0.5155
postapocalyptic 0.5005
lone            0.4886
cyborg          0.4457

==============================
Genre: Adventure
Top 10 Indicative Words:
robin           0.6337
hood            0.5460
research        0.4907
ship            0.4594
stolen          0.4477
area            0.4468
lily            0.4392
carolina        0.4287
marie           0.4240
titan           0.4173

==============================
Genre: Adventure Action Science Fiction
Top 10 Indicative Words:
skywalker       1.0868
jedi            1.0529
luke            0.8900
anakin          0.8726
princess        0.6174
solo            0.5854
han             0.5739
galactic        0.5639
flynn           0.5279
evil            0.5141

==============================
Genre: Adventure Action Thriller
Top 10 Indicative Words:
bond            4.3167
james           2.3822
agent           1.7442
hunt            1.0085
mission         0.9622
blofeld         0.8683
british         0.8586
beautiful       0.7856
prevent         0.7777
revenge         0.7132

==============================
Genre: Adventure Action Thriller Science Fiction
Top 10 Indicative Words:
fight           0.6841
human           0.5791
rico            0.5026
matrix          0.4568
smith           0.4315
dystopian       0.3918
recruited       0.3849
grant           0.3834
biker           0.3808
machine         0.3765

==============================
Genre: Adventure Animation Comedy Family
Top 10 Indicative Words:
bug             0.6364
dump            0.6039
city            0.5568
fox             0.4820
sewer           0.4725
annual          0.4495
adventure       0.4321
animated        0.4209
el              0.4049
yellow          0.4030

==============================
Genre: Adventure Family Fantasy
Top 10 Indicative Words:
witch           0.7773
lucy            0.7210
dorothy         0.6635
lion            0.6579
peter           0.6017
mythical        0.5600
giant           0.5383
evil            0.5308
adventure       0.4635
forever         0.4634

==============================
Genre: Adventure Fantasy Action
Top 10 Indicative Words:
fellowship      0.9360
ring            0.9073
sparrow         0.8197
power           0.6926
thor            0.6476
viking          0.6283
doom            0.5920
bilbo           0.5793
god             0.5688
keeper          0.5269

==============================
Genre: Animation Comedy Family
Top 10 Indicative Words:
penguin         0.8125
jon             0.7725
victor          0.6391
toy             0.5813
hotel           0.5630
farm            0.5456
bunny           0.5356
cool            0.5282
thing           0.5265
mr              0.5262

==============================
Genre: Animation Family
Top 10 Indicative Words:
turtle          0.8031
ordinary        0.7808
circus          0.7567
dream           0.7183
adventure       0.5638
empress         0.5629
monkey          0.5371
garden          0.5361
max             0.5288
island          0.4996

==============================
Genre: Comedy
Top 10 Indicative Words:
kid             1.6723
fraternity      1.5555
wedding         1.4273
friend          1.3592
guy             1.2961
couple          1.2129
looking         1.2124
movie           1.1641
parent          1.1186
school          1.0939

==============================
Genre: Comedy Crime
Top 10 Indicative Words:
need            0.9757
industry        0.8561
frank           0.8290
mafia           0.7346
mistaken        0.6574
plan            0.6224
help            0.6198
criminal        0.6185
party           0.6124
gangster        0.6100

==============================
Genre: Comedy Crime Drama
Top 10 Indicative Words:
pas             0.6394
script          0.4604
lion            0.4101
came            0.3657
depressed       0.3649
dom             0.3647
mouth           0.3541
housewife       0.3519
increasingly    0.3462
crime           0.3415

==============================
Genre: Comedy Drama
Top 10 Indicative Words:
family          1.3457
struggle        1.2749
comedy          1.0970
cope            1.0545
school          1.0361
friendship      0.9441
father          0.8882
playing         0.8771
teenager        0.8380
mother          0.7888

==============================
Genre: Comedy Drama Family
Top 10 Indicative Words:
kit             0.6811
friend          0.6669
simon           0.6319
unpopular       0.4567
fancy           0.4561
mississippi     0.4400
widower         0.4385
marries         0.4331
daniel          0.4150
widow           0.4060

==============================
Genre: Comedy Drama Romance
Top 10 Indicative Words:
love            1.4739
mother          1.2027
meet            1.1781
woman           1.0642
romantic        1.0372
life            1.0342
fall            0.9869
york            0.9618
relationship    0.9111
comedian        0.9014

==============================
Genre: Comedy Family
Top 10 Indicative Words:
holiday         1.1168
christmas       0.9899
family          0.9059
summer          0.8705
dad             0.8243
kid             0.7685
lesson          0.7355
coach           0.7203
canine          0.7169
school          0.7067

==============================
Genre: Comedy Horror
Top 10 Indicative Words:
spider          0.7008
killer          0.6959
classmate       0.6137
group           0.5981
stan            0.5848
fun             0.5552
best            0.5479
malcolm         0.5289
zombie          0.5065
spoof           0.4834

==============================
Genre: Comedy Music
Top 10 Indicative Words:
band            0.9743
rock            0.9453
dewey           0.6606
style           0.6128
finn            0.5636
musical         0.5382
clear           0.5330
finale          0.5086
teacher         0.4990
tell            0.4699

==============================
Genre: Comedy Romance
Top 10 Indicative Words:
woman           2.2186
love            1.8313
relationship    1.6800
wedding         1.5568
fall            1.4224
greg            1.3723
want            1.3261
single          1.1811
jane            1.1632
married         1.1162

==============================
Genre: Comedy Romance Drama
Top 10 Indicative Words:
pregnant        0.8801
maybe           0.7797
kat             0.7142
losing          0.6366
later           0.5833
middleaged      0.5535
stacy           0.5255
going           0.5200
shes            0.5151
patricia        0.4757

==============================
Genre: Crime Drama
Top 10 Indicative Words:
family          0.8937
johnny          0.8262
drug            0.7637
brandon         0.7167
south           0.6621
friend          0.6304
tracy           0.6130
bobby           0.5896
trick           0.5780
writer          0.5729

==============================
Genre: Crime Drama Mystery Thriller
Top 10 Indicative Words:
police          0.8901
campbell        0.8317
serial          0.8314
murder          0.7284
suspect         0.7174
killer          0.6176
uncover         0.5870
investigation   0.5808
corporation     0.5327
investigator    0.5307

==============================
Genre: Crime Drama Thriller
Top 10 Indicative Words:
money           0.9648
crime           0.9381
business        0.9009
bank            0.8003
lecter          0.7643
lou             0.7334
heist           0.7204
desperate       0.7036
cartel          0.6764
sociopathic     0.6616

==============================
Genre: Crime Thriller
Top 10 Indicative Words:
agent           0.5742
jordan          0.5635
mr              0.5589
investigate     0.5471
reviled         0.4598
causing         0.4471
sam             0.4391
inhabitant      0.4159
sin             0.4156
killer          0.3943

==============================
Genre: Documentary
Top 10 Indicative Words:
documentary     1.5742
filmmaker       1.0070
issue           0.8221
michael         0.8036
afghanistan     0.7689
explore         0.7431
health          0.7222
moore           0.7195
global          0.7122
iraq            0.6980

==============================
Genre: Drama
Top 10 Indicative Words:
son             1.8662
story           1.8023
player          1.7969
father          1.6735
life            1.6343
coach           1.5149
drama           1.3005
football        1.2841
jesus           1.2732
california      1.1985

==============================
Genre: Drama Comedy
Top 10 Indicative Words:
way             0.7797
spends          0.7026
overthetop      0.6797
jack            0.6660
wife            0.6416
live            0.6060
tv              0.5579
come            0.5468
actor           0.5280
friend          0.5187

==============================
Genre: Drama Comedy Romance
Top 10 Indicative Words:
love            0.9523
relationship    0.8061
wedding         0.6511
freespirited    0.5945
marriage        0.5528
rachel          0.5496
sally           0.5335
lucas           0.5250
meet            0.4895
way             0.4719

==============================
Genre: Drama Crime
Top 10 Indicative Words:
corleone        1.1810
mafia           1.0935
drug            0.8667
gangster        0.7407
family          0.6183
reformed        0.6112
crime           0.5616
vega            0.5305
manhattan       0.4932
east            0.4917

==============================
Genre: Drama History
Top 10 Indicative Words:
early           1.1713
story           1.1709
true            1.0147
mandela         0.8361
queen           0.7817
reign           0.7231
nation          0.6874
journalist      0.6541
bush            0.6329
iconic          0.6190

==============================
Genre: Drama History War
Top 10 Indicative Words:
war             0.8937
ii              0.8466
bridge          0.7805
germany         0.6610
irish           0.6194
thousand        0.5243
netherlands     0.5228
general         0.4998
hotel           0.4639
world           0.4540

==============================
Genre: Drama Horror Thriller
Top 10 Indicative Words:
marion          0.5299
great           0.5207
daughter        0.4941
rachel          0.4503
possession      0.4177
reef            0.4151
barrier         0.3951
mother          0.3742
soul            0.3733
speak           0.3627

==============================
Genre: Drama Music
Top 10 Indicative Words:
singer          1.5900
rise            0.9203
poverty         0.8604
rock            0.7724
dancer          0.6921
band            0.6767
music           0.6175
film            0.5920
musical         0.5884
benefit         0.5764

==============================
Genre: Drama Music Romance
Top 10 Indicative Words:
jean            0.6841
inspiration     0.5148
rose            0.5098
roger           0.5020
song            0.4662
eddie           0.4620
love            0.4528
francisco       0.4179
dancer          0.4122
underground     0.3870

==============================
Genre: Drama Mystery Thriller
Top 10 Indicative Words:
joseph          0.7099
katie           0.6964
deceit          0.5267
dr              0.5266
sound           0.5146
man             0.4633
firm            0.4514
reclusive       0.4505
piece           0.4172
work            0.3947

==============================
Genre: Drama Romance
Top 10 Indicative Words:
love            1.9395
affair          1.8226
life            1.5323
daughter        1.2001
girl            1.1954
fall            1.0995
lover           1.0480
career          0.9799
housewife       0.9658
meet            0.9584

==============================
Genre: Drama Thriller
Top 10 Indicative Words:
affair          0.9760
boy             0.8390
swan            0.7075
president       0.6468
married         0.6368
room            0.6162
story           0.6049
cia             0.5879
fails           0.5867
disappears      0.5863

==============================
Genre: Drama Thriller Crime
Top 10 Indicative Words:
religious       0.7640
family          0.6694
death           0.6061
teenager        0.6011
father          0.5898
murder          0.5474
chart           0.5388
money           0.5371
police          0.4452
erin            0.4436

==============================
Genre: Drama War
Top 10 Indicative Words:
war             1.0546
vietnam         0.7372
biography       0.6539
shakespeare     0.6382
army            0.5890
setting         0.5862
japanese        0.5715
duty            0.5161
joey            0.4955
enlist          0.4755

==============================
Genre: Horror
Top 10 Indicative Words:
zombie          1.3287
terrifying      1.0974
house           1.0178
krueger         1.0022
spirit          0.9262
group           0.8622
strange         0.8524
supernatural    0.8469
freddy          0.8388
cannibal        0.8068

==============================
Genre: Horror Mystery
Top 10 Indicative Words:
premonition     1.3857
sidney          1.0897
woodsboro       0.8281
terrifying      0.6861
past            0.6334
save            0.6302
sarah           0.6255
death           0.5929
gale            0.5092
student         0.5016

==============================
Genre: Horror Mystery Thriller
Top 10 Indicative Words:
emily           0.8366
murder          0.7830
horrifying      0.6901
people          0.6759
trapped         0.6109
mystery         0.6054
ship            0.5928
prostitute      0.5802
target          0.5794
museum          0.5760

==============================
Genre: Horror Thriller
Top 10 Indicative Words:
group           1.6220
lake            1.5086
jason           1.4918
myers           1.1823
horror          1.1781
house           1.1346
jamie           1.0473
spirit          1.0274
freddy          1.0188
ghost           1.0138

==============================
Genre: Romance Comedy
Top 10 Indicative Words:
date            1.2207
tank            0.5277
girlfriend      0.5110
anna            0.5092
executive       0.5036
lucy            0.4979
romance         0.4776
mall            0.4663
meet            0.4525
clueless        0.4516

==============================
Genre: Romance Drama
Top 10 Indicative Words:
love            0.9507
meet            0.6547
year            0.6129
terminal        0.5650
dana            0.5410
gilbert         0.5180
separated       0.4708
second          0.4670
pressure        0.4340
sean            0.4301

==============================
Genre: Science Fiction
Top 10 Indicative Words:
clone           0.6728
survivor        0.5865
satellite       0.5531
spacecraft      0.4586
aid             0.4365
tyrant          0.4179
merciless       0.4091
nuclear         0.4032
ocean           0.4025
launched        0.4006

==============================
Genre: Thriller
Top 10 Indicative Words:
married         0.5226
jack            0.5126
extreme         0.5108
clique          0.5091
london          0.4971
alice           0.4468
cesar           0.4426
silver          0.4377
mentally        0.4352
younger         0.4349

==============================
Genre: Thriller Crime Drama
Top 10 Indicative Words:
mob             0.6471
trouble         0.6456
sullivan        0.6390
bennett         0.5565
gambling        0.5321
investment      0.5079
risky           0.4963
police          0.4915
truth           0.4484
contract        0.4444

==============================
Genre: Thriller Drama
Top 10 Indicative Words:
trafficking     0.5134
circumstance    0.4951
connie          0.4783
plane           0.4506
hour            0.4330
violent         0.4212
maria           0.4082
affair          0.4059